# Generated by Django 3.2.7 on 2021-12-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20211218_2009'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], default='Full-time', max_length=30),
        ),
    ]
