# Generated by Django 3.2.7 on 2021-12-19 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.TextField()),
                ('type_of', models.CharField(choices=[('event', 'event'), ('activity', 'activity'), ('reminder', 'reminder'), ('other', 'other')], default='event', max_length=30)),
            ],
        ),
    ]
